(()=>{
  const V={
    wsl:{title:'What is Windows Subsystem for Linux (WSL)?',url:'https://learn.microsoft.com/en-us/shows/one-dev-minute/what-is-the-windows-subsystem-for-linux-wsl--one-dev-question',scope:'Visual orientation for Linux-on-Windows workflow.',provider:'Microsoft Learn'},
    git:{title:'GitHub pull request workflow',url:'https://www.youtube.com/watch?v=nCKdihvneS0',scope:'See a beginner pull-request workflow.',provider:'GitHub'},
    docker:{title:'Docker intro and container overview',url:'https://www.docker.com/resources/docker-intro-and-overview-on-demand-training/',scope:'Reinforce the container mental model and local workflow.',provider:'Docker'},
    airflow:{title:'Airflow 3 ETL/ELT workshop',url:'https://www.astronomer.io/events/webinars/etl-elt-airflow-3-workshop-video/',scope:'Visualize an end-to-end Airflow 3 workflow.',provider:'Astronomer'},
    decorators:{title:'Writing functional DAGs with decorators',url:'https://www.astronomer.io/events/webinars/writing-functional-dags-with-decorators-video/',scope:'See TaskFlow/decorator DAG authoring and dependencies.',provider:'Astronomer'},
    scheduling:{title:'Scheduling in Airflow',url:'https://www.astronomer.io/events/webinars/scheduling-in-airflow-comprehensive-intro-video/',scope:'Visualize schedules, logical intervals and scheduling behavior.',provider:'Astronomer'},
    backfills:{title:'Airflow 3 backfills and developer experience',url:'https://www.astronomer.io/events/webinars/apache-airflow-3-optimize-your-pipeline-developer-experience-video/',scope:'See supported backfills, DAG versioning and log access.',provider:'Astronomer'},
    delta:{title:'Delta Lake transaction log tech talk',url:'https://delta.io/blog/2020-03-13-diving-into-delta-lake-online-tech-talk-series/',scope:'Reinforce ACID, transaction-log metadata and time travel.',provider:'Delta Lake'},
    sparkArch:{title:'Apache Spark architecture explainer',url:'https://www.youtube.com/watch?v=iXVIPQEGZ9Y',scope:'See driver, executors, partitions, jobs, stages, tasks and shuffles.',provider:'Spark architecture explainer'},
    sparkUi:{title:'Mastering the Spark UI',url:'https://community.databricks.com/t5/databricks-tv/mastering-the-sparkui-on-databricks-2024-04-30/ba-p/79909',scope:'Use Spark UI to reinforce query-plan and performance diagnosis.',provider:'Databricks'},
    kafka:{title:'Apache Kafka fundamentals',url:'https://www.youtube.com/watch?v=B5j3uNBH8X4',scope:'Visualize topics, partitions, brokers, producers, consumers and offsets.',provider:'Confluent'},
    schema:{title:'Schema Registry: Maintain Data Quality Across Data Streams',url:'https://developer.confluent.io/courses/governing-data-streams/schema-registry/',scope:'Official 5-minute video covering registering, evolving and validating schemas in Schema Registry.',provider:'Confluent Developer'},
    structured:{title:'Spark Structured Streaming design strategies',url:'https://www.youtube.com/watch?v=_guCMLpJQ74',scope:'See practical Structured Streaming design patterns.',provider:'Databricks / Spark community'},
    checkpoints:{title:'Streaming checkpoints and recovery',url:'https://community.databricks.com/t5/databricks-tv/dive-into-streaming-checkpoints-amp-best-practices-1-25-2023/ba-p/98943',scope:'Reinforce checkpointing, recovery and stateful streaming.',provider:'Databricks'},
    fabric:{title:'Microsoft Fabric platform overview',url:'https://learn.microsoft.com/en-us/shows/fabric-tech-talk-fridays/unlocking-data-analytics-at-scale-with-microsoft-fabric',scope:'Current visual orientation to the Fabric platform.',provider:'Microsoft Learn'},
    onelake:{title:'Exploring OneLake in Microsoft Fabric',url:'https://learn.microsoft.com/en-us/shows/fabric-tech-talk-fridays/no-walls-just-data-exploring-onelake-in-microsoft-fabric',scope:'See OneLake and shortcuts in the Fabric UI.',provider:'Microsoft Learn'},
    factory:{title:'Use Data Factory pipelines in Microsoft Fabric',url:'https://learn.microsoft.com/en-us/shows/learn-live/learn-together-microsoft-fabric-wave-1-ep104-use-data-factory-pipelines-in-microsoft-fabric',scope:'See pipelines, Copy activity, runs and monitoring.',provider:'Microsoft Learn'},
    fabricGit:{title:'Bringing Fabric items into source control (Git)',url:'https://learn.microsoft.com/en-us/shows/fabric-tech-talk-fridays/bringing-microsoft-fabric-items-into-source-control-git',scope:'See workspace Git integration and collaboration workflow.',provider:'Microsoft Learn'},
    secure:{title:'Secure and govern Microsoft Fabric',url:'https://learn.microsoft.com/en-us/shows/fabric-tech-talk-fridays/secure-and-govern-mastering-microsoft-fabric-for-the-enterprise',scope:'Visualize lineage, access controls, audit and governance.',provider:'Microsoft Learn'},
    dbt:{title:'dbt 101: A Real-time Look Into dbt Cloud',url:'https://www.getdbt.com/resources/webinars/dbt-101-live-april-session',scope:'Official on-demand visual walkthrough of dbt use cases, platform workflow and project concepts; use after the internal lesson.',provider:'dbt Labs'},
    cdc:{title:'Kafka Connect + CDC',url:'https://developer.confluent.io/courses/data-pipelines/kafka-data-ingestion-with-cdc/',scope:'Reinforce query-based vs log-based CDC and database-to-Kafka ingestion patterns.',provider:'Confluent Developer'},
    fabricSpark:{title:'Use Apache Spark in Microsoft Fabric',url:'https://learn.microsoft.com/en-us/shows/learn-live/get-started-with-microsoft-fabric-ep02-use-apache-spark-in-microsoft-fabric',scope:'See Fabric Spark configuration, notebooks, DataFrames, Spark SQL and job scenarios.',provider:'Microsoft Learn'},
    warehouse:{title:'Get started with data warehouses in Microsoft Fabric',url:'https://learn.microsoft.com/en-us/shows/learn-live/learn-together-microsoft-fabric-wave-2-ep206-get-started-with-data-warehouses-in-microsoft-fabric',scope:'See warehouse creation, T-SQL serving, security and monitoring.',provider:'Microsoft Learn'},
    realtime:{title:'Democratizing Real-Time Intelligence in Microsoft Fabric',url:'https://learn.microsoft.com/en-us/shows/ask-the-expert/democratizing-real-time-intelligence-in-microsoft-fabric',scope:'See Eventstream/Eventhouse/KQL context for streaming and event-driven scenarios.',provider:'Microsoft Learn'},
    cost:{title:'Strategic capacity monitoring and cost analysis for Fabric',url:'https://learn.microsoft.com/en-us/shows/data-exposed/strategic-capacity-monitoring-and-cost-analysis-for-sql-database-in-fabric-data-exposed',scope:'Use for capacity metrics and cost-awareness orientation.',provider:'Microsoft Learn'}
  };
  window.OPTIONAL_VIDEO_MAP={
    'C3-00-L02':[V.wsl],'C3-00-L04':[V.git],'C3-00-L11':[V.docker],
    'C3-02-L03':[V.dbt],'C3-02-L10':[V.dbt],
    'C3-03-L02':[V.airflow],'C3-03-L03':[V.airflow,V.decorators],'C3-03-L04':[V.scheduling],'C3-03-L06':[V.airflow],'C3-03-L07':[V.backfills],'C3-03-L08':[V.airflow],'C3-03-L10':[V.scheduling],'C3-03-L12':[V.backfills],
    'C3-04-L08':[V.delta],'C3-04-L11':[V.delta],
    'C3-05-L01':[V.sparkArch],'C3-05-L02':[V.sparkArch],'C3-05-L10':[V.sparkArch,V.sparkUi],'C3-05-L11':[V.sparkUi],'C3-05-L13':[V.sparkUi],'C3-05-L14':[V.sparkUi],
    'C3-06-L01':[V.structured],'C3-06-L02':[V.kafka],'C3-06-L03':[V.kafka],'C3-06-L04':[V.kafka],'C3-06-L05':[V.schema],'C3-06-L06':[V.cdc],'C3-06-L08':[V.structured],'C3-06-L09':[V.structured],'C3-06-L10':[V.structured],'C3-06-L11':[V.checkpoints],'C3-06-L13':[V.checkpoints],
    'C3-07-L03':[V.fabric,V.onelake],'C3-07-L04':[V.onelake],'C3-07-L05':[V.factory],'C3-07-L06':[V.factory],'C3-07-L07':[V.fabricSpark],'C3-07-L08':[V.fabricSpark],'C3-07-L09':[V.warehouse],'C3-07-L10':[V.realtime],'C3-07-L12':[V.fabricGit],'C3-07-L13':[V.factory],'C3-07-L14':[V.secure],'C3-07-L15':[V.cost]
  };
})();
